### ISSUE TITLE
Updating folioreader in epub_viewer

### ISSUE THREAD

**Issue by syedecryptr** [JideGuru/Folioreader-Android#3]
Hi, do you have any plans of updating the epub_viewer with this current Folioreader since it contains a bookmark facility and the current epub_viewer is using an old version of [Folioreader](https://github.com/JideGuru/epub_viewer/blob/master/android/build.gradle) ?

**Comment by JideGuru** [comment]
Hello @syedecryptr , I was working on moving the base library to Readium but I might just continue Folioreader as Readium requires a lot of work. So yes, I'll update it

**Comment by syedecryptr** [comment]
That makes sense, thanks.

**Comment by dymxin** [comment]
> Hi, do you have any plans of updating the epub_viewer with this current Folioreader since it contains a bookmark facility and the current epub_viewer is using an old version of [Folioreader](https://github.com/JideGuru/epub_viewer/blob/master/android/build.gradle) ?

Can I contact you? @syedecryptr

**Comment by syedecryptr** [comment]
> > Hi, do you have any plans of updating the epub_viewer with this current Folioreader since it contains a bookmark facility and the current epub_viewer is using an old version of [Folioreader](https://github.com/JideGuru/epub_viewer/blob/master/android/build.gradle) ?
> 
> Can I contact you? @syedecryptr

sure connect with me on [twitter](https://twitter.com/decryptr_syed)
